### ISSUE TITLE
When user deletes all bookmarks, app dies

### ISSUE THREAD

**Issue by gtracy** [gtracy/madbus#38]
The app simply shoes a blank screen and throws the following console error:

TypeError: Cannot read properties of undefined (reading 'stop_code')
    at ou (StopList.js:98:55)
    at aa (react-dom.production.min.js:157:137)
    at Wa (react-dom.production.min.js:180:154)
    at qs (react-dom.production.min.js:269:343)
    at Ol (react-dom.production.min.js:250:347)
    at Ml (react-dom.production.min.js:250:278)
    at Pl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

**Comment by gtracy** [comment]
Plan is to cover this case and inject the defaults when we detect this case.
